export const NAVIGATION_PATHS = {
  //PRIVATE PATHS
  AUTHENTICATED: 'authenticated',
  DASHBOARD: 'dashboard',

  PATIENTS: 'patients',
  PATIENTS_CREATE: 'create',
  PATIENTS_UPDATE: 'update/:patientId',

  USERS: 'users',
  USERS_CREATE: 'create',
  USERS_UPDATE: 'update/:userId',

  //PUBLIC PATHS
  AUTH: 'auth',
  AUTH_SIGN_IN: 'sign-in',
  AUTH_SIGN_UP: 'sign-up',

  NOT_FOUND: 'not-found',
};

export const FULL_NAVIGATION_PATHS = {
  //Dashboard
  DASHBOARD: `/${NAVIGATION_PATHS.AUTHENTICATED}/${NAVIGATION_PATHS.DASHBOARD}`,

  //Patients
  PATIENTS_LIST: `/${NAVIGATION_PATHS.AUTHENTICATED}/${NAVIGATION_PATHS.PATIENTS}`,
  PATIENTS_CREATE: `/${NAVIGATION_PATHS.AUTHENTICATED}/${NAVIGATION_PATHS.PATIENTS}/${NAVIGATION_PATHS.PATIENTS_CREATE}`,
  PATIENTS_UPDATE: `/${NAVIGATION_PATHS.AUTHENTICATED}/${
    NAVIGATION_PATHS.PATIENTS
  }/${NAVIGATION_PATHS.PATIENTS_UPDATE.replace(':patientId', '')}`,

  //users
  USERS_LIST: `/${NAVIGATION_PATHS.AUTHENTICATED}/${NAVIGATION_PATHS.USERS}`,
  USERS_CREATE: `/${NAVIGATION_PATHS.AUTHENTICATED}/${NAVIGATION_PATHS.USERS}/${NAVIGATION_PATHS.USERS_CREATE}`,
  USERS_UPDATE: `/${NAVIGATION_PATHS.AUTHENTICATED}/${
    NAVIGATION_PATHS.USERS
  }/${NAVIGATION_PATHS.USERS_UPDATE.replace(':userId', '')}`,

  //Auth
  AUTH_SIGN_IN: `/${NAVIGATION_PATHS.AUTH}/${NAVIGATION_PATHS.AUTH_SIGN_IN}`,
  AUTH_SIGN_UP: `/${NAVIGATION_PATHS.AUTH}/${NAVIGATION_PATHS.AUTH_SIGN_UP}`,

  //Not Found
  NOT_FOUND: `/${NAVIGATION_PATHS.NOT_FOUND}`,
};
