export const NAVIGATION_PATHS = {
  ORDERS: 'orders',
  ORDERS_CREATE: 'create',
  ORDERS_UPDATE: 'update/:orderId',

  PATIENTS: 'patients',
  PATIENTS_CREATE: 'create',
  PATIENTS_UPDATE: 'update/:patientId',

  DOCTORS: 'doctors',
  DOCTORS_CREATE: 'create',
  DOCTORS_UPDATE: 'update/:doctorId',

  NOT_FOUND: 'not-found',
};

export const FULL_NAVIGATION_PATHS = {
  ORDERS_LIST: `/${NAVIGATION_PATHS.ORDERS}`,
  ORDERS_CREATE: `/${NAVIGATION_PATHS.ORDERS}/${NAVIGATION_PATHS.ORDERS_CREATE}`,
  ORDERS_UPDATE: `/${NAVIGATION_PATHS.ORDERS}/${NAVIGATION_PATHS.ORDERS_UPDATE.replace(
    ':orderId',
    ''
  )}`,

  PATIENTS_LIST: `/${NAVIGATION_PATHS.PATIENTS}`,
  PATIENTS_CREATE: `/${NAVIGATION_PATHS.PATIENTS}/${NAVIGATION_PATHS.PATIENTS_CREATE}`,
  PATIENTS_UPDATE: `/${NAVIGATION_PATHS.PATIENTS}/${NAVIGATION_PATHS.PATIENTS_UPDATE.replace(
    ':patientId',
    ''
  )}`,

  DOCTORS_LIST: `/${NAVIGATION_PATHS.DOCTORS}`,
  DOCTORS_CREATE: `/${NAVIGATION_PATHS.DOCTORS}/${NAVIGATION_PATHS.DOCTORS_CREATE}`,
  DOCTORS_UPDATE: `/${NAVIGATION_PATHS.DOCTORS}/${NAVIGATION_PATHS.DOCTORS_UPDATE.replace(
    ':doctorId',
    ''
  )}`,

  NOT_FOUND: `/${NAVIGATION_PATHS.NOT_FOUND}`,
};
